name: Checks

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check links using container
        uses: sskoklev/action-my-broken-link-checker@v1
        with:
          url: https://github.com/sskoklev/Muffet-Test
          pages_path: ""
          cmd_params: "--skip-tls-verification"
          run_timeout: 10
          debug: true
